#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'colorize'
require 'prism'

class TestComments < Test::Unit::TestCase
  def test_comments
    error_count = 0
    `git ls-files`.lines.map(&:chomp) # Get all files in git...
                  .select { /\.rb$/.match?(it) || _bang_ruby?(it) }
                  .each do |filename|
      line_number = 0
      File.readlines(filename).each do |line|
        line_number += 1
        next unless line.include? '#'

        comments = Prism.parse_comments(line)
        next unless (data = comments.shift)

        offset = data.location.start_offset
        comment = line[offset..-1]
        code = line[0...offset]
        next if code.strip.empty?
        next unless %r{['"/)\}\]]}.match?(comment)

        error_count += 1
        puts "#{filename}:#{line_number}:#{line}"
      end
    end
    if error_count > 0
      print 'Remove these characters from side comments: '.blue
      puts %q('"/\)}]).red
      flunk
    end
  end

  private

  def _bang_ruby?(filename)
    return false if /\.\w*$/.match?(filename) ||
                    File.directory?(filename) ||
                    !File.executable?(filename)

    /^#!.*\bruby$/.match? File.read(filename, 80).lines[0].rstrip
  end
end
